[libraries]
osvvm.files = [
    'vunit/vunit/vhdl/osvvm/RandomBasePkg.vhd',
    'vunit/vunit/vhdl/osvvm/MemoryPkg.vhd',
    'vunit/vunit/vhdl/osvvm/ScoreboardPkg_int_c.vhd',
    'vunit/vunit/vhdl/osvvm/TextUtilPkg.vhd',
    'vunit/vunit/vhdl/osvvm/OsvvmGlobalPkg.vhd',
    'vunit/vunit/vhdl/osvvm/MessagePkg.vhd',
    'vunit/vunit/vhdl/osvvm/RandomProcedurePkg.vhd',
    'vunit/vunit/vhdl/osvvm/TbUtilPkg.vhd',
    'vunit/vunit/vhdl/osvvm/ScoreboardPkg_int.vhd',
    'vunit/vunit/vhdl/osvvm/ResolutionPkg.vhd',
    'vunit/vunit/vhdl/osvvm/demo/AlertLog_Demo_Hierarchy.vhd',
    'vunit/vunit/vhdl/osvvm/demo/AlertLog_Demo_Global.vhd',
    'vunit/vunit/vhdl/osvvm/demo/Demo_Rand.vhd',
    'vunit/vunit/vhdl/osvvm/OsvvmContext.vhd',
    'vunit/vunit/vhdl/osvvm/ReportPkg.vhd',
    'vunit/vunit/vhdl/osvvm/TranscriptPkg.vhd',
    'vunit/vunit/vhdl/osvvm/ResizePkg.vhd',
    'vunit/vunit/vhdl/osvvm/MessageListPkg.vhd',
    'vunit/vunit/vhdl/osvvm/NamePkg.vhd',
    'vunit/vunit/vhdl/osvvm/RandomPkg.vhd',
    'vunit/vunit/vhdl/osvvm/SortListPkg_int.vhd',
    'vunit/vunit/vhdl/osvvm/AlertLogPkg.vhd',
    'vunit/vunit/vhdl/osvvm/VendorCovApiPkg.vhd',
    'vunit/vunit/vhdl/osvvm/ScoreboardPkg_slv.vhd',
    'vunit/vunit/vhdl/osvvm/ScoreboardPkg_slv_c.vhd',
    'vunit/vunit/vhdl/osvvm/CoveragePkg.vhd',
    'vunit/vunit/vhdl/osvvm/ScoreboardGenericPkg.vhd',
    'vunit/vunit/vhdl/osvvm/NameStorePkg.vhd',
]
vunit_lib.files = [
    'vunit/vunit/vhdl/run/test/tb_watchdog.vhd',
    'vunit/vunit/vhdl/run/test/run_tests.vhd',
    'vunit/vunit/vhdl/run/test/tb_run.vhd',
    'vunit/vunit/vhdl/run/src/runner_pkg.vhd',
    'vunit/vunit/vhdl/run/src/run.vhd',
    'vunit/vunit/vhdl/run/src/run_api.vhd',
    'vunit/vunit/vhdl/run/src/run_types.vhd',
    'vunit/vunit/vhdl/run/src/run_deprecated_pkg.vhd',
    'vunit/vunit/vhdl/data_types/src/queue_pkg.vhd',
    'vunit/vunit/vhdl/data_types/src/codec_builder.vhd',
    'vunit/vunit/vhdl/data_types/src/string_ptr_pool_pkg.vhd',
    'vunit/vunit/vhdl/data_types/src/integer_vector_ptr_pool_pkg.vhd',
    'vunit/vunit/vhdl/data_types/src/codec.vhd',
    'vunit/vunit/vhdl/data_types/src/api/external_integer_vector_pkg.vhd',
    'vunit/vunit/vhdl/data_types/src/api/external_string_pkg.vhd',
    'vunit/vunit/vhdl/data_types/src/queue_pool_pkg.vhd',
    'vunit/vunit/vhdl/data_types/src/data_types_context.vhd',
    'vunit/vunit/vhdl/data_types/src/codec_builder-2008p.vhd',
    'vunit/vunit/vhdl/data_types/src/integer_array_pkg.vhd',
    'vunit/vunit/vhdl/data_types/src/types.vhd',
    'vunit/vunit/vhdl/data_types/src/dict_pkg.vhd',
    'vunit/vunit/vhdl/data_types/src/codec-2008p.vhd',
    'vunit/vunit/vhdl/data_types/src/queue_pkg-body.vhd',
    'vunit/vunit/vhdl/data_types/src/string_ptr_pkg.vhd',
    'vunit/vunit/vhdl/data_types/src/integer_array_pkg-body.vhd',
    'vunit/vunit/vhdl/data_types/src/integer_vector_ptr_pkg.vhd',
    'vunit/vunit/vhdl/data_types/src/byte_vector_ptr_pkg.vhd',
    'vunit/vunit/vhdl/data_types/src/queue_pkg-2008p.vhd',
    'vunit/vunit/vhdl/path/test/tb_path.vhd',
    'vunit/vunit/vhdl/path/src/path.vhd',
    'vunit/vunit/vhdl/vunit_run_context.vhd',
    'vunit/vunit/vhdl/logging/src/log_levels_pkg-body.vhd',
    'vunit/vunit/vhdl/logging/src/print_pkg.vhd',
    'vunit/vunit/vhdl/logging/src/logger_pkg.vhd',
    'vunit/vunit/vhdl/logging/src/log_levels_pkg.vhd',
    'vunit/vunit/vhdl/logging/src/ansi_pkg.vhd',
    'vunit/vunit/vhdl/logging/src/logger_pkg-body.vhd',
    'vunit/vunit/vhdl/logging/src/log_handler_pkg-body.vhd',
    'vunit/vunit/vhdl/logging/src/location_pkg.vhd',
    'vunit/vunit/vhdl/logging/src/log_handler_pkg.vhd',
    'vunit/vunit/vhdl/logging/src/location_pkg-body-2008m.vhd',
    'vunit/vunit/vhdl/logging/src/file_pkg.vhd',
    'vunit/vunit/vhdl/logging/src/print_pkg-body.vhd',
    'vunit/vunit/vhdl/logging/src/log_deprecated_pkg.vhd',
    'vunit/vunit/vhdl/core/src/stop_body_2008p.vhd',
    'vunit/vunit/vhdl/core/src/stop_pkg.vhd',
    'vunit/vunit/vhdl/core/src/core_pkg.vhd',
    'vunit/vunit/vhdl/string_ops/src/string_ops.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_axi_statistics_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_axi_stream.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_sync_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_avalon_master.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_std_logic_checker.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_bus_master_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_wishbone_master.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_axi_stream_protocol_checker.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_axi_write_slave.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_axi_lite_master.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_uart.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_axi_read_slave.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_ram_master.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_avalon_stream_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_wishbone_slave.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_avalon.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_axi_slave_private_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_avalon_stream.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_memory.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_memory_utils_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/test/tb_avalon_slave.vhd',
    'vunit/vunit/vhdl/verification_components/src/sync_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/wishbone_master.vhd',
    'vunit/vunit/vhdl/verification_components/src/stream_slave_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/wishbone_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/stream_master_pkg-body.vhd',
    'vunit/vunit/vhdl/verification_components/src/sync_pkg-body.vhd',
    'vunit/vunit/vhdl/verification_components/src/uart_master.vhd',
    'vunit/vunit/vhdl/verification_components/src/axi_stream_protocol_checker.vhd',
    'vunit/vunit/vhdl/verification_components/src/stream_slave_pkg-body.vhd',
    'vunit/vunit/vhdl/verification_components/src/axi_stream_monitor.vhd',
    'vunit/vunit/vhdl/verification_components/src/avalon_master.vhd',
    'vunit/vunit/vhdl/verification_components/src/axi_stream_master.vhd',
    'vunit/vunit/vhdl/verification_components/src/stream_master_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/avalon_stream_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/avalon_source.vhd',
    'vunit/vunit/vhdl/verification_components/src/axi_slave_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/axi_stream_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/wishbone_slave.vhd',
    'vunit/vunit/vhdl/verification_components/src/uart_slave.vhd',
    'vunit/vunit/vhdl/verification_components/src/avalon_sink.vhd',
    'vunit/vunit/vhdl/verification_components/src/memory_pkg-body.vhd',
    'vunit/vunit/vhdl/verification_components/src/axi_slave_private_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/uart_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/axi_lite_master_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/axi_statistics_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/memory_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/signal_checker_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/avalon_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/axi_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/bus_master_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/std_logic_checker.vhd',
    'vunit/vunit/vhdl/verification_components/src/axi_read_slave.vhd',
    'vunit/vunit/vhdl/verification_components/src/avalon_slave.vhd',
    'vunit/vunit/vhdl/verification_components/src/axi_stream_private_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/axi_write_slave.vhd',
    'vunit/vunit/vhdl/verification_components/src/axi_stream_slave.vhd',
    'vunit/vunit/vhdl/verification_components/src/bus_master_pkg-body.vhd',
    'vunit/vunit/vhdl/verification_components/src/vc_context.vhd',
    'vunit/vunit/vhdl/verification_components/src/ram_master.vhd',
    'vunit/vunit/vhdl/verification_components/src/bus2memory.vhd',
    'vunit/vunit/vhdl/verification_components/src/memory_utils_pkg.vhd',
    'vunit/vunit/vhdl/verification_components/src/axi_lite_master.vhd',
    'vunit/vunit/vhdl/array/src/array_pkg.vhd',
    'vunit/vunit/vhdl/dictionary/src/dictionary.vhd',
    'vunit/vunit/vhdl/vunit_context.vhd',
    'vunit/vunit/vhdl/check/test/test_support.vhd',
    'vunit/vunit/vhdl/check/src/check_api.vhd',
    'vunit/vunit/vhdl/check/src/checker_pkg.vhd',
    'vunit/vunit/vhdl/check/src/check.vhd',
    'vunit/vunit/vhdl/check/src/check_deprecated_pkg.vhd',
    'vunit/vunit/vhdl/check/src/checker_pkg-body.vhd',
    'vunit/vunit/vhdl/com/test/more_constants.vhd',
    'vunit/vunit/vhdl/com/test/custom_types.vhd',
    'vunit/vunit/vhdl/com/test/constants.vhd',
    'vunit/vunit/vhdl/com/src/com_types.vhd',
    'vunit/vunit/vhdl/com/src/com_messenger.vhd',
    'vunit/vunit/vhdl/com/src/com.vhd',
    'vunit/vunit/vhdl/com/src/com_support.vhd',
    'vunit/vunit/vhdl/com/src/com_api.vhd',
    'vunit/vunit/vhdl/com/src/com_debug_codec_builder.vhd',
    'vunit/vunit/vhdl/com/src/com_deprecated.vhd',
    'vunit/vunit/vhdl/com/src/com_common.vhd',
    'vunit/vunit/vhdl/com/src/com_context.vhd',
    'vunit/vunit/vhdl/com/src/com_string.vhd',
    'vunit/vunit/vhdl/random/src/random_pkg.vhd',
    'vunit/tests/acceptance/artificial/vhdl/bool_driver.vhd',
    'vunit/tests/acceptance/artificial/vhdl/other_file_tests.vhd',
    'vunit/tests/acceptance/dependencies/pkg.vhd',
    'vunit/tests/acceptance/dependencies/pkg_body1.vhd',
    'vunit/tests/acceptance/dependencies/pkg_body2.vhd',
]